#!/usr/bin/env ruby
# frozen_string_literal: true

# Resolve relative to this launcher, including when invoked through ~/.digital_cinema_tools/.bin.
load File.expand_path('vendor/dcp_inspect/dcp_inspect', __dir__)
