#!/usr/bin/env bash
set -e

# These functions are also sourced by the platform regression tests.
dct_detect_linux() {
  local ID='' ID_LIKE=''
  [[ -r $1 ]] || return 1
  . "$1"
  case "$ID" in
    omarchy) echo omarchy ;;
    arch) echo arch ;;
    debian) echo debian ;;
    ubuntu|linuxmint|pop) echo ubuntu ;;
    fedora|rhel|centos|rocky|almalinux) echo redhat ;;
    *)
      case " $ID_LIKE " in
        *' arch '*) echo arch ;;
        *' ubuntu '*) echo ubuntu ;;
        *' debian '*) echo debian ;;
        *' fedora '*|*' rhel '*) echo redhat ;;
        *) return 1 ;;
      esac ;;
  esac
}

dct_arch_packages() {
  echo base-devel ruby-build rust cmake git curl ca-certificates openssl libyaml readline zlib gmp libffi gdbm util-linux xerces-c xmlsec sox fd ffmpeg
}

dct_install_arch_packages() {
  local platform=$1
  shift
  if [[ $platform == omarchy ]] && command -v omarchy >/dev/null 2>&1
  then
    omarchy pkg add "$@" || return 1
  else
    sudo pacman -S --needed "$@" || return 1
  fi
  # Check installed state, including package-manager helpers that return success
  # without installing every requested package.
  local package
  for package in "$@"; do
    pacman -Q "$package" >/dev/null 2>&1 || return 1
  done
}

dct_prepare_private_ruby() {
  local version=$1 prefix=$2
  if ! "$prefix/bin/ruby" -ropenssl -rpsych -e 'exit(RUBY_VERSION == ARGV[0] ? 0 : 1)' "$version" >/dev/null 2>&1
  then
    echo "Ruby: Building private Ruby $version (no changes to mise or global Ruby selection)"
    RUBY_CONFIGURE_OPTS='--disable-install-doc' MAKE_OPTS='-j4' ruby-build "$version" "$prefix" || return 1
  fi
  "$prefix/bin/ruby" -ropenssl -rpsych -e 'exit(RUBY_VERSION == ARGV[0] ? 0 : 1)' "$version"
}

dct_write_ruby_launcher() {
  local ruby_bin=$1 source=$2 destination=$3 temporary
  [[ ! -d $destination ]] || { echo "Command destination is a directory: $destination" >&2; return 1; }
  if [[ -e $destination && ! -L $destination ]] && ! grep -q '^# Digital Cinema Tools private Ruby launcher$' "$destination"
  then
    echo "Refusing to replace unmanaged command: $destination" >&2
    return 1
  fi
  temporary=$(mktemp "${destination}.XXXXXX") || return 1
  {
    echo '#!/usr/bin/env bash'
    echo '# Digital Cinema Tools private Ruby launcher'
    echo 'unset GEM_HOME GEM_PATH RUBYOPT RUBYLIB'
    printf 'export PATH=%q:"$PATH"\n' "$(dirname "$ruby_bin")"
    printf 'exec %q %q "$@"\n' "$ruby_bin" "$source"
  } > "$temporary"
  chmod 755 "$temporary"
  mv -f "$temporary" "$destination"
}

# Sourcing this file exposes functions without running the installer.
if [[ ${BASH_SOURCE[0]} != "$0" ]]; then return 0; fi

setup_version='v1.2026.10.02'
#
# Usage:
#
#   * To install run
#       wget https://git.io/digital-cinema-tools-setup && bash digital-cinema-tools-setup
#     in a terminal
#
#
#   * For updates or re-runs run
#       digital-cinema-tools-setup
#     in a terminal
#
# This setup script will install everything required (batteries included) to run
#
#   * dcp_inspect:  Inspect and validate digital cinema packages (DCPs)
#                   See https://github.com/wolfgangw/backports#readme
#
# and a number of other digital cinema-related tools:
#
#   * db_adjust_for_dolby_fader_ref.rb: Calculate adjustments for Dolby CP650/750 7.0 setting
#   * dc_crypto_context.rb:             Check certificate chains for digital cinema compliance
#   * decrypt_kdm.rb:                   Decrypt Interop/SMPTE KDMs
#   * make-dc-certificate-chain.rb:     Generate an example digital cinema compliant certificate chain
#   * public_key_thumbprint.rb:         Compute dnQualifier/public key thumbprint of a X.509 certificate
#   * signature_check.rb:               Check XML signatures of DCP infrastructure documents
#   * x509_extract.rb:                  Extract X.509 certificates from digital cinema documents
#   * x509_inspect.rb:                  Inspect X.509 certificates
#   * xsd-check.rb:                     Validate XML documents against Schema definitions
#
# This installer supports Omarchy / Arch / Debian / Ubuntu / Fedora / macOS
# Needs a working network connection
#
# It tries hard not to break anything and to respect the existing environment.
# You can run it multiple times, should anything go wrong during a setup run (network problems etc.)
#
# Wolfgang Woehl 2012-2023
#
#
# Location of self
#
setup_dirname=$( cd "$(dirname "${BASH_SOURCE[0]}")" && pwd )
setup_basename=$(basename ${BASH_SOURCE[0]})
setup_fullpath="$setup_dirname/$setup_basename"
echo "$setup_basename $setup_version"

bashrc=$HOME/.bashrc
inputrc=$HOME/.inputrc
script_runner=$(whoami)

basedir=$HOME/.digital_cinema_tools
libdir=$basedir/.lib
bindir=$basedir/.bin

# Ruby version management: rbenv
rbenv_url="https://github.com/sstephenson/rbenv.git"
export RBENV_ROOT=$libdir/.rbenv
rbenv_dir=$RBENV_ROOT
rbenv_plugins_dir=$rbenv_dir/plugins

# Ruby build system: ruby-build
rubybuild_url="https://github.com/sstephenson/ruby-build.git"
rubybuild_dir=$rbenv_plugins_dir/ruby-build
ruby_version='3.4.6'
gemrc=$HOME/.gemrc

# Handle SMPTE and Interop trackfiles: AS-DCP Lib
asdcplib_url="https://github.com/cinecert/asdcplib.git"
asdcplib_version='2.13.2'
asdcplib_version_tag='rel_2_13_2'
asdcplib_dir=$libdir/asdcplib
asdcplib_build_dir="$asdcplib_dir/build"
asdcplib_install_dir=$bindir/asdcplib

# Digital cinema tools distribution:
dist_url="https://github.com/wolfgangw/digital_cinema_tools_distribution.git"
dist_dir=$libdir/digital_cinema_tools_distribution

errors=()
exec_shell_required=false

command_exists() {
  type "$1" &> /dev/null
}

location_exists() {
  [ -e "$1" ]
}

string_includes() {
  [[ "$1" =~ "$2" ]]
}

echo_last() {
  local arr=("${!1}")
  echo ${arr[${#arr[@]}-1]}
}

remove_if_exists() {
  if location_exists $1
  then
    rm -rf $1
  fi
}

location_is_git_repo() {
  location_exists "$1" && location_exists "$1/.git" && [ -d "$1/.git" ]
}


# Only linux systems in mind for now
if [[ $MACHTYPE =~ linux || $MACHTYPE =~ darwin ]]
then
  echo "Platform: $MACHTYPE supported"
else
  echo "Platform: This installer supports only linux and darwin systems"
  exit 1
fi


# Check and bail out if the installer is run with root privileges
if [ $script_runner == "root" ]
then
  echo
  echo 'Do not run this installer as root'
  echo 'Do not run this installer via sudo'
  echo 'This installer will ask for privileges if and when required'
  echo
  echo 'That said:'
  echo
  echo 'If you know exactly why you would want to'
  echo "continue as root -- usually you don't want to --"
  read -p 'then type root and press [ENTER]: ' run_as_root_confirm
  if ! [ "$run_as_root_confirm" == "root" ]
  then
    exit 1
  fi
  echo 'Continuing as root ...'
  sleep 3
fi


#
# Which OS distribution are we on?
#
os_dist=$(dct_detect_linux /etc/os-release) || os_dist=''
if [[ -z $os_dist ]] && command_exists sw_vers
then
  os_dist=macos
fi

# Bail out if non-supported OS distribution
if ! [ -z $os_dist ]
then
  echo "OS: $os_dist"
else
  echo 'OS not supported'
  exit 1
fi

# Bail out if we don't have sudo
if command_exists sudo
then
  case $os_dist in
    debian)
      if echo `groups` | grep sudo &>/dev/null
      then
        echo "$os_dist: sudo OK"
      else
        echo "$os_dist: sudo: Need to be member of the sudo group."
        echo
        echo 'Run the following 3 commands:'
        echo
        echo "su -                  # will prompt for your root password"
        echo "adduser `whoami` sudo # Adds you to the sudo group"
        echo 'exit                  # exits from root account'
        echo
        echo 'Then log out or reboot'
        echo 'Then re-run digital-cinema-tools-setup'
        echo
        exit 1
      fi
      ;;
    macos)
      echo "$os_dist: sudo not required"
  esac
else
  echo 'Required command "sudo" not found. Please install sudo'
  exit 1
fi

# Depending on which OS we're on set the required packager and switches
# to install a basic set of packages from distribution sources
case $os_dist in
  omarchy|arch)
    query='pacman'
    query_params='-Q'
    packager='pacman'
    packager_params='-S --needed'
    packages_required=( $(dct_arch_packages) )
    packager_prep=''
    ;;
  debian|ubuntu)
    query='dpkg-query'
    query_params='-s'
    packager='apt-get'
    packager_params='-y install'
    # build-essential odd ..
    packages_required=( autoconf patch build-essential rustc libssl-dev libyaml-dev libreadline-dev zlib1g-dev libgmp-dev libncurses-dev libffi-dev libgdbm6t64 libgdbm-dev libdb-dev uuid-dev cmake curl libxerces-c-dev xmlsec1 libreadline-dev libssl-dev sox git libffi-dev fd-find )
    packager_prep="$packager update"
    ;;
  redhat)
    query='rpm'
    query_params='--query'
    packager='yum'
    packager_params='-y install'
    packages_required=( make automake autoconf cmake gcc gcc-c++ rustc wget xerces-c-devel xmlsec1 xmlsec1-openssl libyaml-devel readline-devel zlib-devel libgmp-devel libncurses5-devel libgdbm6 libgdbm6-devel uuid-devel openssl-devel sox git libffi-devel fd-find )
    packager_prep="$packager update" # erm, FIXME
    ;;
  macos)
    query='brew'
    query_params='list'
    packager='brew'
    packager_params='install'
    packages_required=( cmake git xerces-c openssl@3 gmp libyaml readline rust sox fd )
    packager_prep="$packager update"
esac


# Audio analysis needs FFmpeg. Keep an existing installation and verify its
# filters after installing the inspector's Ruby dependencies.
if ! command_exists ffmpeg
then
  case $os_dist in
    redhat) packages_required+=( ffmpeg-free ) ;;
    omarchy|arch) ;; # Already included in the Arch package list.
    *) packages_required+=( ffmpeg ) ;;
  esac
fi

# Check for the presence of required basic distribution packages
if command_exists $query && command_exists $packager
then
  packages_missing=()
  for package in ${packages_required[@]}
  do
    if $query $query_params $package &> /dev/null
    then
      echo "$package: OK"
    else
      echo "$package: Installation required"
      packages_missing+=($package)
    fi
  done
  if [ ${#packages_missing[@]} -gt 0 ]
  then
    echo
    echo "$setup_basename: ${#packages_missing[@]} packages missing"
    echo "$setup_basename: ${packages_missing[@]}"
    echo
    case $os_dist in
      debian|ubuntu)
        echo "Please enter your password" ;;
      redhat)
        echo 'Please enter your root password' ;;
    esac

    # Install packages
    case $os_dist in
      omarchy|arch)
        if ! dct_install_arch_packages "$os_dist" "${packages_missing[@]}"
        then
          echo 'Could not install required packages. See the package-manager error above, resolve it, and rerun setup.' >&2
          exit 1
        fi
        ;;
      debian|ubuntu|redhat)
        if ! [ -z "$packager_prep" ]
        then
          if ! sudo $packager_prep
          then
            errors+=("$setup_basename: Failed to prepare package installation") && echo_last errors[@]
          else
            echo "$setup_basename: Package preparation OK"
          fi
        fi
        if ! sudo $packager $packager_params "${packages_missing[@]}"
        then
          errors+=("$packager: Failed to install basic requirements") && echo_last errors[@]
          sudo -K # drop sudo privileges
          exit 1
        else
          echo "$packager: OK"
        fi
        sudo -K
        ;;
      macos)
        if ! [ -z "$packager_prep" ]
        then
          if ! $packager_prep
          then
            errors+=("$setup_basename: Failed to prepare package installation") && echo_last errors[@]
          else
            echo "$setup_basename: Package preparation OK"
          fi
        fi
        if ! $packager $packager_params "${packages_missing[@]}"
        then
          errors+=("$packager: Failed to install basic requirements") && echo_last errors[@]
          exit 1
        else
          echo "$packager: OK"
        fi
        ;;
    esac
  fi
else
  errors+=("$setup_basename: Required packager tools not found: $query/$packager. Exiting") && echo_last errors[@]
  exit 1
fi


# Set up directories for digital cinema tools
if ! location_exists $basedir ; then mkdir $basedir ; fi
if ! location_exists $libdir ; then mkdir $libdir ; fi
if ! location_exists $bindir ; then mkdir $bindir ; fi


# Check for $bindir and inclusion in PATH
if string_includes $PATH "$bindir"
then
  echo "PATH: $bindir available in PATH"
fi
if grep "export PATH=$bindir:" $bashrc
then
  echo "bashrc: $bindir already included. OK"
else
  echo "bashrc: Adding $bindir to PATH"
  echo '' >> $bashrc
  echo "# $setup_basename: Add $bindir to PATH" >> $bashrc
  echo "export PATH=$bindir:"'$PATH' >> $bashrc
  exec_shell_required=true
fi


export PATH="$bindir:$PATH"

# On Arch, keep Ruby private to these tools instead of competing with mise.
if [[ $os_dist == omarchy || $os_dist == arch ]]
then
  unset GEM_HOME GEM_PATH RUBYOPT RUBYLIB
  private_ruby_dir="$libdir/ruby-$ruby_version"
  if ! dct_prepare_private_ruby "$ruby_version" "$private_ruby_dir"
  then
    echo 'Could not prepare the private Ruby runtime' >&2
    exit 1
  fi
  export PATH="$private_ruby_dir/bin:$bindir:$PATH"
  export DCT_RUBY_MANAGER=direct
else
export DCT_RUBY_MANAGER=rbenv
# rbenv
if command_exists rvm
then
  echo
  echo "Sorry. This installer insists on using rbenv for Ruby version management."
  echo "You have RVM installed and those 2 won't co-exist peacefully, so there."
  echo "If you want to continue remove RVM from your system and re-run this installer."
  echo "Apologies for the obtrusive hassle."
  echo
  exit 1
fi
if command_exists rbenv
then
  echo "rbenv: OK"
else
  if location_exists $rbenv_dir && location_is_git_repo $rbenv_dir
  then
    echo "rbenv: Repository exists"
    cd $rbenv_dir
    if ! git pull
    then
      errors+=("rbenv: Failed to pull updates") && echo_last errors[@]
    fi
    if string_includes $PATH "$rbenv_dir/bin"
    then
      echo "rbenv: PATH includes rbenv bin dir"
    else
      errors+=("rbenv: PATH does not include rbenv bin dir") && echo_last errors[@]
    fi
  else
    echo "rbenv: Installing"
    remove_if_exists $rbenv_dir
    if ! git clone $rbenv_url $rbenv_dir
    then
      errors+=("rbenv: Failed to clone repository. Try again later") && echo_last errors[@]
    fi

    echo '' >> $bashrc
    echo "# $setup_basename: rbenv environment" >> $bashrc
    echo "export RBENV_ROOT=$rbenv_dir" >> $bashrc
    echo "export PATH=$rbenv_dir/bin:"'$PATH' >> $bashrc
    echo 'eval "$(rbenv init -)"' >> $bashrc
    RBENV_ROOT=$rbenv_dir
    PATH=$rbenv_dir/bin:$PATH
    eval "$(rbenv init -)"
    exec_shell_required=true

    if command_exists rbenv
    then
      echo "rbenv: OK"
    else
      echo "rbenv: Command 'rbenv' not found"
      exit 1
    fi
  fi
fi


# gems: ri/rdoc switches
if [ -e $gemrc ]
then
  if grep '^gem: --no-ri --no-rdoc' $gemrc
  then
    echo 'gemrc: OK'
  else
    echo 'gemrc: Keeping changed gemrc (--no-ri/rdoc switches will not be added)'
  fi
else
  echo 'gem: --no-document' > $gemrc
fi


# ruby-build (as rbenv plugin)
if location_exists $rbenv_dir
then
  if ! location_exists $rbenv_plugins_dir
  then
    mkdir $rbenv_plugins_dir
  fi
else
  mkdir -p $rbenv_plugins_dir # eh? FIXME
fi
cd $rbenv_plugins_dir
if location_is_git_repo $rubybuild_dir
then
  cd $rubybuild_dir
  if ! git pull --ff-only origin master
  then
    errors+=("ruby-build: Failed to pull updates. Try again later") && echo_last errors[@]
  else
    echo 'ruby-build: OK'
  fi
else
  remove_if_exists $rubybuild_dir
  echo 'ruby-build: Installing'
  if ! git clone $rubybuild_url
  then
    errors+=("ruby-build: Failed to clone repository. Try again later") && echo_last errors[@]
  else
    echo 'ruby-build: OK'
  fi
fi


# Try to install a ruby version
# Explicitly set global $ruby_version
if command_exists rbenv
then
  if ! rbenv global $ruby_version
  then
    echo 'rbenv: Required ruby not installed'
  fi
  if [[ `rbenv version` =~ $ruby_version ]] && command_exists ruby
  then
    echo "Ruby: OK"
  else
    echo "Ruby: Installing ... This will take a while"
    if ! CONFIGURE_OPTS="--disable-install-doc" MAKE_OPTS="-j4" rbenv install $ruby_version --verbose
    then
      errors+=("Ruby: Failed to install requested version") && echo_last errors[@]
    else
      rbenv global $ruby_version
      rbenv rehash
      echo "Ruby: $( rbenv version )"
      echo 'Ruby: OK'
    fi
  fi
else
  errors+=("Ruby: Failed to install ruby (Required command rbenv not found)") && echo_last errors[@]
fi


fi # Arch private Ruby / rbenv

# Nokogiri (with c14n)
nokogiri_c14n=false
if command_exists gem
then
  if gem list -i nokogiri &> /dev/null
  then
    echo 'Nokogiri: Found installed gem'
  else
    # Install Nokogiri gem
    if ! gem install nokogiri
    then
      errors+=("Nokogiri: Failed to install required gem nokogiri") && echo_last errors[@]
    else
      if [[ ${DCT_RUBY_MANAGER:-rbenv} == rbenv ]]; then rbenv rehash; fi
      echo 'Nokogiri: Installed gem nokogiri'
    fi
  fi

  # Check for C14N support
  if gem list -i nokogiri &> /dev/null
  then
    if command_exists ruby && ruby -e 'exit(RUBY_VERSION == ARGV[0] ? 0 : 1)' "$ruby_version"
    then
      if ruby -e "require 'rubygems'; require 'nokogiri'; exit(Nokogiri::XML::Document.new.respond_to?(:canonicalize) ? 0 : 1)"
      then
        nokogiri_c14n=true
        echo 'Nokogiri: C14N support present'
      else
        nokogiri_c14n=false
        errors+=("Nokogiri: Installed version does not support C14N") && echo_last errors[@]
      fi
    else
      errors+=("Nokogiri: Could not test Nokogiri C14N support (Required ruby version not found)") && echo_last errors[@]
    fi
    if $nokogiri_c14n
    then
      echo 'Nokogiri: OK'
    else
      errors+=("Nokogiri: There is a problem with the installed version of Nokogiri. Consider removing your installed version of Nokogiri and re-run this installer") && echo_last errors[@]
    fi
  fi

else
  errors+=("Nokogiri: Failed to install Nokogiri (Required command gem not found)") && echo_last errors[@]
fi # Nokogiri


# asdcplib
cd $libdir
if command_exists asdcp-info && command_exists asdcp-unwrap && command_exists kmuuidgen && [[ "$(asdcp-info -V 2>&1)" == *"$asdcplib_version"* ]]
then
  echo "asdcplib: OK ($asdcplib_version)"
  if location_exists $asdcplib_dir && location_is_git_repo $asdcplib_dir
  then
    cd $asdcplib_dir
    git checkout master
    if ! git pull
    then
      errors+=("asdcplib: Failed to pull updates") && echo_last errors[@]
    fi
  else
    echo "asdcplib: Is installed but repo $asdcplib_dir not found. Not changing anything"
  fi
else
  echo "asdcplib: Installing $asdcplib_version ..."
  remove_if_exists $asdcplib_dir
  mkdir $asdcplib_dir && cd $asdcplib_dir
  if ! git clone $asdcplib_url $asdcplib_dir
  then
    errors+=("asdcplib: Failed to clone repository") && echo_last errors[@]
  else
    git checkout $asdcplib_version_tag
    mkdir $asdcplib_build_dir && cd $asdcplib_build_dir
    cmake_options=()
    case $os_dist in
      omarchy|arch)
        cmake_options+=( -DCMAKE_POLICY_VERSION_MINIMUM=3.5 ) ;;
      ubuntu)
        echo "asdcplib ($os_dist): FIXME patching CMakeLists.txt"
        sed -i 's/cmake_minimum_required(VERSION 3.0)/cmake_minimum_required(VERSION 3.5)/' ../CMakeLists.txt
        export LDFLAGS="-L/usr/lib/$(dpkg-architecture -qDEB_HOST_MULTIARCH)" ;;
      redhat)
        export LDFLAGS='' ;;
      macos)
        echo "asdcplib ($os_dist): FIXME patching CMakeLists.txt"
        sed -i '' -e 's/cmake_minimum_required(VERSION 3.0)/cmake_minimum_required(VERSION 3.5)/' ../CMakeLists.txt
    esac
    if cmake "${cmake_options[@]}" -DCMAKE_INSTALL_PREFIX="$asdcplib_install_dir" .. && make -j4 && make install
    then
      asdcplib_build=ok
    else
      asdcplib_build=fail
      errors+=("asdcplib: Can not create build directory") && echo_last errors[@]
    fi
    if [ "$asdcplib_build" = 'ok' ]
    then
      cd $bindir
      for tool in $asdcplib_install_dir/bin/*
      do
        if [ -e $bindir/$(basename ${tool}) ]
        then
          rm $bindir/$(basename ${tool})
          echo "asdcplib: Updating $(basename ${tool})"
          ln -s $tool .
        else
          echo "asdcplib: Add to $bindir: $(basename ${tool})"
          ln -s $tool .
        fi
      done # asdcplib
    else
      errors+=("asdcplib: Building asdcplib failed") && echo_last errors[@]
    fi
  fi
fi # asdcplib installed or built


# Digital Cinema Tools distribution
cd $libdir
if location_is_git_repo $dist_dir
then
  cd $dist_dir
  echo "Digital cinema tools distribution: Pulling updates ..."
  if ! git pull --ff-only origin master
  then
    errors+=("Digital cinema tools distribution: Failed to pull updates. Try again later") && echo_last errors[@]
  fi
else
  remove_if_exists $dist_dir
  if ! git clone $dist_url
  then
    errors+=("Digital cinema tools distribution: Failed to clone repository. Try again later") && echo_last errors[@]
  else
    echo 'Digital cinema tools distribution: Repository OK'
  fi
fi
# Update $bindir entries for distribution
if location_exists $dist_dir
then
  cd $dist_dir
  tools=( $( cat toollist ) )
  cd $bindir
  for tool in ${tools[@]}
  do
    if [[ $os_dist == omarchy || $os_dist == arch ]] && [[ $tool == *.rb || $tool == dcp_inspect ]]
    then
      if ! dct_write_ruby_launcher "$private_ruby_dir/bin/ruby" "$dist_dir/$tool" "$bindir/$tool"
      then
        errors+=("Could not install private Ruby launcher for $tool") && echo_last errors[@]
      fi
      continue
    fi
    if [ -e $bindir/$tool ] && command_exists $tool
    then
      # Special case: setup might be hanging around here from a previous run:
      # When distribution setup would have failed and the downloaded setup been moved to $bindir.
      # Replace with repo version
      if [[ $tool =~ $setup_basename ]] && [ ! -L $setup_fullpath ]
      then
        echo "Digital cinema tools distribution: Replacing setup with repo version"
        rm $bindir/$tool
        ln -s $dist_dir/$tool .
      else
        echo "Digital cinema tools distribution: $tool OK"
      fi
    else
      echo "Digital cinema tools distribution: Add to $bindir: $tool"
      ln -s $dist_dir/$tool .
    fi
  done
else
  errors+=("Digital cinema tools distribution: Failed to update $bindir. Repository missing") && echo_last errors[@]
fi
# dcp_inspect: runtime gems and complete release validation
if ! bash "$dist_dir/scripts/install-dcp-inspect-dependencies.sh"
then
  errors+=("dcp_inspect: Release or runtime dependency setup failed") && echo_last errors[@]
fi
# Done: Digital Cinemas Tools Distribution


# Fastpath for tab-completion
if [ -e $inputrc ]
then
  # Leave any existing setting untouched
  if grep "^set show-all-if-ambiguous on$" $inputrc
  then
    echo 'Tab completion: Fastpath set to on. Leaving untouched. OK'
  elif grep "^set show-all-if-ambiguous off$" $inputrc
  then
    echo 'Tab completion: Fastpath set to off. Leaving untouched. OK'
  fi
else
  touch $inputrc
  echo 'Tab completion: Setting fastpath to on'
  echo "# $setup_basename: This will make completions show up after 1 TAB hit" >> $inputrc
  echo 'set show-all-if-ambiguous on' >> $inputrc
  exec_shell_required=true
fi


# Setup done
echo

if [ ${#errors[@]} -gt 0 ]
then
  echo 'There were errors:'
  for e in "${errors[@]}"
  do
    echo "Error: $e"
  done
  echo
  exit 1
fi


# FIXME On re-runs in already working environments this is mis-leading
if $exec_shell_required
then
  echo '  ---------------------------------------------------'
  echo ' |                                                   |'
  echo ' |  To finish the installation run                   |'
  echo ' |                                                   |'
  case $os_dist in
    omarchy|arch|debian|ubuntu|redhat)
      echo ' |    exec $SHELL                                    |'
      echo ' |                                                   |'
      echo ' |  in this terminal now (mind the "$" in "$SHELL")  |'
      ;;
    macos)
      echo ' |    exec /bin/bash                                 |'
  esac
  echo ' |                                                   |'
  echo '  ---------------------------------------------------'
  echo
fi

echo "$setup_basename ($setup_version): Done"
echo

exit 0
